1. Create a nested list which contains the name, age and race of 10 people each. Turn this list to a dataframe.

In [3]:
import pandas as pd
list1=[["ije","1","oma"],["lil", "1","uju"],["nwa","3", "seun"], ["amy","4" ,"nora"], ["aa","5", "bb"],["yoruba","6" ,"ihhhh"], ["igbo","7","ibibio"], ["shhhh","8", "lollll"],["flyyy", "9","disah"],["whhh","10","shyff"]]
list1

[['ije', '1', 'oma'],
 ['lil', '1', 'uju'],
 ['nwa', '3', 'seun'],
 ['amy', '4', 'nora'],
 ['aa', '5', 'bb'],
 ['yoruba', '6', 'ihhhh'],
 ['igbo', '7', 'ibibio'],
 ['shhhh', '8', 'lollll'],
 ['flyyy', '9', 'disah'],
 ['whhh', '10', 'shyff']]

2. Label the columns with the appropriate column names

In [4]:
name=pd.DataFrame(list1, columns=["Name","Age", "Race"])
name

Name Age    Race
0     ije   1     oma
1     lil   1     uju
2     nwa   3    seun
3     amy   4    nora
4      aa   5      bb
5  yoruba   6   ihhhh
6    igbo   7  ibibio
7   shhhh   8  lollll
8   flyyy   9   disah
9    whhh  10   shyff

3. Add a new column to your dataframe called weight and enter values for it.

In [5]:
name["Weight"]=[12,13,24,15,17,19,20,15,15,20]
name

Name Age    Race  Weight
0     ije   1     oma      12
1     lil   1     uju      13
2     nwa   3    seun      24
3     amy   4    nora      15
4      aa   5      bb      17
5  yoruba   6   ihhhh      19
6    igbo   7  ibibio      20
7   shhhh   8  lollll      15
8   flyyy   9   disah      15
9    whhh  10   shyff      20

4. Change the name of the column for "weight" to "height". Feel free to use any method you find. 

In [6]:
name.rename(columns={"Weight":"Height"}, inplace=True)
name

Name Age    Race  Height
0     ije   1     oma      12
1     lil   1     uju      13
2     nwa   3    seun      24
3     amy   4    nora      15
4      aa   5      bb      17
5  yoruba   6   ihhhh      19
6    igbo   7  ibibio      20
7   shhhh   8  lollll      15
8   flyyy   9   disah      15
9    whhh  10   shyff      20

5. Change the row index to another indexing of your choice.

In [7]:
name.index=("a","b","c","d","e","f","g","h","k","l")
name

Name Age    Race  Height
a     ije   1     oma      12
b     lil   1     uju      13
c     nwa   3    seun      24
d     amy   4    nora      15
e      aa   5      bb      17
f  yoruba   6   ihhhh      19
g    igbo   7  ibibio      20
h   shhhh   8  lollll      15
k   flyyy   9   disah      15
l    whhh  10   shyff      20

6. Select/display only the age and race columns

In [8]:
name[["Age","Race"]]

Age    Race
a   1     oma
b   1     uju
c   3    seun
d   4    nora
e   5      bb
f   6   ihhhh
g   7  ibibio
h   8  lollll
k   9   disah
l  10   shyff

7. Select/display the first five names and their age 

In [9]:
name.loc["a":"e"]

Name Age  Race  Height
a  ije   1   oma      12
b  lil   1   uju      13
c  nwa   3  seun      24
d  amy   4  nora      15
e   aa   5    bb      17

8. Select all rows but only the third column

In [10]:
name[["Race"]]

Race
a     oma
b     uju
c    seun
d    nora
e      bb
f   ihhhh
g  ibibio
h  lollll
k   disah
l   shyff

9. Write some code to return the row index back to the default numbering before it was changed. Use your researching skills.

In [11]:
name.reset_index(inplace=True,drop=True)
name

Name Age    Race  Height
0     ije   1     oma      12
1     lil   1     uju      13
2     nwa   3    seun      24
3     amy   4    nora      15
4      aa   5      bb      17
5  yoruba   6   ihhhh      19
6    igbo   7  ibibio      20
7   shhhh   8  lollll      15
8   flyyy   9   disah      15
9    whhh  10   shyff      20

10. Create a dataframe from the dictionary above. Using the dataframe, select books with ratings not less than 200000

In [13]:
chimamanda = {"Books":["Americanah", "Half of a Yellow Sun", "Purple Hibiscus",
                    "The Thing Around Your Neck", "We Should All Be Feminists"], 
             "Ratings":[297972, 120131, 5116, 32064, 204882]}

In [14]:
next1=pd.DataFrame(chimamanda)
next1

Books  Ratings
0                  Americanah   297972
1        Half of a Yellow Sun   120131
2             Purple Hibiscus     5116
3  The Thing Around Your Neck    32064
4  We Should All Be Feminists   204882

In [15]:
next1.loc[[0,4 ]] #used in selecting out rating not less than 200000 using their index

Books  Ratings
0                  Americanah   297972
4  We Should All Be Feminists   204882

11. Create a numpy array with data type boolean

In [17]:
import numpy as np
b=np.array([[False,True,False], [True,False,True]])
b.dtype

dtype('bool')

In [18]:
# 12. Convert the following array to an integer

a = np.array([[True, False, False],
              [True, True, True],
              [False, False, False]])

p = a.astype(int)

print(p)

[[1 0 0]
 [1 1 1]
 [0 0 0]]


In [19]:
#13. Stack these numpy arrays - vertically and horizontally

a = np.array([[7, 8, 9],
              [10, 11, 12]])

aa = np.array([[1, 2, 3],
               [4, 5, 6]])
harray=np.hstack((a,aa))
varray=np.vstack((a,aa))
print(harray)
print(varray)

[[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]
[[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


14. Create 2 3D arrays, add them together to create a new array, then sort the new array.

In [23]:
import numpy as np
yet=np.array([[[1,2,3],[2,3,4]], [[3,4,5], [4,5,6]]])
yep=np.array([[[3,5,6],[1,0,1]],[[2,0,2],[3,0,3]]])
newArray=np.add(yet,yep)
newArray

array([[[4, 7, 9],
        [3, 3, 5]],

       [[5, 4, 7],
        [7, 5, 9]]])

In [24]:
print (np.sort(newArray))

[[[4 7 9]
  [3 3 5]]

 [[4 5 7]
  [5 7 9]]]


In [21]:
#15. Using step slicing, slice the array below from any position using 3 steps

a = np.array([5, 8, 7, 1, 0, 9, 4, 2, 6, 3])
a = np.array([5, 8, 7, 1, 0, 9, 4, 2, 6, 3])
mp=a[2:9:2]
mp


array([7, 0, 4, 6])